<a href="https://colab.research.google.com/github/DeltSystem32/CIS3187-Assignment/blob/master/CIS3187_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Business Intelligence Coursework: Neural Network
## By Daniel Anthony Cilia 315499(M)
---



## Project Imports



In [0]:
import pandas as pd

## Read and parse data

Obtain testing and traning data from two CSV files in the project repository on Github.

The data consists of 5-bit numbers being mapped to 3-bit via the Boolean function ¬ABC.

Converters are used to map values to string upon import in order to retain all leading zeros.

#### Training set:

In [0]:
training_data_url = "https://raw.githubusercontent.com/DeltSystem32/CIS3187-Assignment/master/training_data.csv?token=AIW66N7AHOHHI377456TMX26BCJUK"
training_df = pd.read_csv(training_data_url, converters={'input': lambda x: str(x), 'output': lambda x: str(x)})
training_df

Num  input output
0     1  00000    100
1     3  00010    100
2     4  00011    100
3     5  00100    101
4     7  00110    101
5     8  00111    101
6     9  01000    110
7    10  01001    110
8    11  01010    110
9    12  01011    110
10   14  01101    111
11   15  01110    111
12   17  10000    000
13   18  10001    000
14   19  10010    000
15   20  10011    000
16   21  10100    001
17   22  10101    001
18   24  10111    001
19   25  11000    010
20   26  11001    010
21   27  11010    010
22   29  11100    011
23   30  11101    011
24   31  11110    011
25   32  11111    011

#### Testing set:

In [0]:
testing_data_url = "https://raw.githubusercontent.com/DeltSystem32/CIS3187-Assignment/master/testing_data.csv?token=AIW66NY3IT4SWVHC3YKJL7K6BDTKC"
testing_df = pd.read_csv(testing_data_url, converters={'input': lambda x: str(x), 'output': lambda x: str(x)})
testing_df

Num  input output
0    2  00001    100
1    6  00101    101
2   13  01100    111
3   16  01111    111
4   23  10110    001
5   28  11011    010

#### Size of data:

In [0]:
print("Size of training set: " + str(len(training_df)))
print("Size of testing set: "+ str(len(testing_df)))

Size of training set: 26
Size of testing set: 6


## MLP Parameters

The Neural Network to be implemented will consist of the following:
*   **Number of input neurons**: 5
*   **Number of output neurons**: 3
*   **Number of hidden layers**: 1
*   **Number of hidden neurons**: 4
*   **Error threshold**: 0.2
*   **Learning rate**: 0.2
*   **Maximum number of epochs**: 999
*   **Transformation function**: Sigmoid

In [0]:
class parameters:
  NUM_IN_NEURONS = 5
  NUM_OUT_NEURONS = 3
  NUM_HIDDEN_LAYERS = 1
  NUM_HIDDEN_NEURONS = 4
  ERROR_THRESHOLD = 0.2
  LEARNING_RATE = 0.2
  MAX_EPOCHS = 999

### Sigmoid function implementation

The method will be called *transform()* so as to remain generic so that it can be 'hotswapped' with other transformation functions if the need arises.

In [0]:
 import math

 def transform(x):
    #sigmoid
    return 1 / (1 + math.exp(-x))
    

#add to MLP parameters
parameters.transform = transform

## MLP Class

Begin by implementing feed-forward functionality.

In [136]:
import numpy as np

class MLP:

  layers = None
  inputs = None
  wH = None

  def generate_weights(self):
      return np.random.uniform(low=0,high=1, size=(parameters.NUM_IN_NEURONS,parameters.NUM_HIDDEN_NEURONS))

  def transform_matrix(self, net):
    return [[parameters.transform(j) for j in i] for i in net]

  #feed-forward
  def feedforward(self, wH, inputs):
    print('wh: ', wH)
    print('inputs: ', inputs)
    netH = inputs.dot(wH)
    print(netH)
    outh = self.transform_matrix(netH)
    print(outh)
    


  def __init__(self, input):
    input = str(input)
    if len(input) != 5:
      raise Exception('Input is not 5 bit')

    inputs = np.empty(shape=(1,parameters.NUM_IN_NEURONS))
    input = np.array(list(input))
    inputs[0, :] = input

    wH = self.generate_weights()

    self.feedforward(wH, inputs)


  
mlp = MLP(10001)
 




wh:  [[0.14685585 0.44703379 0.85297776 0.67139761]
 [0.12956925 0.43794794 0.29933082 0.23438916]
 [0.8012788  0.92283391 0.75059399 0.14097324]
 [0.51485227 0.16175955 0.92795175 0.2571529 ]
 [0.18968608 0.91094699 0.68643021 0.89214779]]
inputs:  [[1. 0. 0. 0. 1.]]
[[0.33654193 1.35798078 1.53940797 1.56354541]]
[[0.5833502715795476, 0.7954313248244265, 0.8233786442732265, 0.8268615072252022]]
